export const ADD_NUMBER_DIFFICULTY = "ADD_NUMBER_DIFFICULTY";
export const ADD_FETCHED_DATA = "ADD_FETCHED_DATA";
export const UPDATE_SCORE = "UPDATE_SCORE";
export const UPDATE_CURRENT_QUESTION_NUMBER = "UPDATE_CURRENT_QUESTION_NUMBER";
export const RESET_STATE = "RESET_STATE"